### ISSUE TITLE
License

### ISSUE THREAD

**Issue by billyrrr** [exyte/LiquidSwipe#2]
Hi, the code seems amazing. I was wondering if I can use your source code for my project, and how I should attribute it. Thanks.

**Comment by ystrot** [comment]
Hi @billyrrr,

Thanks! I've added a license file: https://github.com/exyte/LiquidSwipe/blob/master/LICENSE. It's just a regular MIT license, so you're free to use source code in your project.

**Comment by billyrrr** [comment]
Thank you!
