### ISSUE TITLE
Buttons inside subviews

### ISSUE THREAD

**Issue by interior-night** [exyte/LiquidSwipe#3]
Hi, thanks for the great work.

When I change your example to include views (instead of iterating over a rectangle's foreground colour), I find that buttons and list items in those views appear to be un-clickable/hard to click. Changing the views z-index doesn't appear to help. Any idea how to get around this?

**Comment by f3dm76** [comment]
Hey @transat, sorry for this ultra late response, but are you still having issues with your buttons? If you still do, would you please share your code with me so I can reproduce and try to help?
